language: python
python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"

virtualenv:
  system_site_packages: true

before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt 
  - sudo apt-get -y install liblapack-dev libblas-dev gfortran

install:
  - pip install -r requirements.txt

script: python test.py
