language: python
python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"

before_install:
  - sudo apt-get -y install liblapack-dev libblas-dev gfortran

install:
  - pip install -r requirements.txt

script: python test.py
